#!/usr/bin/env python
try:
    import proxy
    proxy.main()
except KeyboardInterrupt:
    print("\nInterrupt recieved. Exiting now...")
except ImportError:
    print("\n\nCannot locate main file proxy.py.")
